---
stages:
  - build
  - test

variables:
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  LC_ALL: en_US.UTF-8

swift-5-1-macOS-10-15-3-build:
  stage: build
  tags:
    - macos-10.15.3-19D76
    - swift-5.1
  script:
    - swift build -Xswiftc -DCRYPTO_IN_SWIFTPM_FORCE_BUILD_API -c release
  except:
    - tags

swift-5-1-macOS-10-15-3-test:
  stage: test
  tags:
    - macos-10.15.3-19D76
    - swift-5.1
  script:
    - >
      swift test
      -Xswiftc -DCRYPTO_IN_SWIFTPM_FORCE_BUILD_API
      --enable-code-coverage 2>&1 | xcpretty --report junit
    - >
      xcrun llvm-cov report
      -ignore-filename-regex=Test
      -instr-profile .build/x86_64-apple-macosx/debug/codecov/default.profdata
      .build/x86_64-apple-macosx/debug/swift-cryptoPackageTests.xctest/Contents/MacOS/swift-cryptoPackageTests
  coverage: '/(\d+\.\d+)%\z/'
  artifacts:
    reports:
      junit: build/reports/junit.xml
  except:
    - tags
