//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftCrypto open source project
//
// Copyright (c) 2020 Apple Inc. and the SwiftCrypto project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.md for the list of SwiftCrypto project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

@testable import ServerCrypto
import XCTest

let singleCertificate = """
-----BEGIN CERTIFICATE-----
MIIDkjCCAxigAwIBAgICEAMwCgYIKoZIzj0EAwIwgZ8xCzAJBgNVBAYTAlVTMRAw
DgYDVQQIDAdBbGFiYW1hMRMwEQYDVQQHDApIdW50c3ZpbGxlMT4wPAYDVQQKDDVT
Y2llbmNlIEFwcGxpY2F0aW9ucyBJbnRlcm5hdGlvbmFsIENvcnBvcmF0aW9uIChT
QUlDKTEpMCcGA1UEAwwgU0FJQyBJU0EgTGFiIEludGVybWVkaWF0ZSBDQSAtIDEw
HhcNMjAwMTAxMDAwMDAzWhcNMjEwMTEwMDAwMDAzWjCBmjELMAkGA1UEBhMCVVMx
EDAOBgNVBAgMB0FsYWJhbWExEzARBgNVBAcMCkh1bnRzdmlsbGUxPjA8BgNVBAoM
NVNjaWVuY2UgQXBwbGljYXRpb25zIEludGVybmF0aW9uYWwgQ29ycG9yYXRpb24g
KFNBSUMpMSQwIgYDVQQDDBtzYWljLWNvbXBvbmVudC1pb3MtYXBwLTAwMDEwdjAQ
BgcqhkjOPQIBBgUrgQQAIgNiAASXBlukZ/u/QiLq5VgvlkTLjS4cRnhJSQSAif95
H/H0Fm2DRqBsaTpCJYr3EMkNohr6qHLlgjVRDwy+O1/zVK/HpXXbmpNEU74P4xg4
r3jWdHW5432UiaUglQM28olDdWOjggEoMIIBJDAMBgNVHRMBAf8EAjAAMB0GA1Ud
DgQWBBR60KiIlshytdzR0XbInm9EFtZUnzCBxQYDVR0jBIG9MIG6gBR3/CjaQWDs
kvwoWP3ILmoqpU8dCaGBnaSBmjCBlzELMAkGA1UEBhMCVVMxEDAOBgNVBAgMB0Fs
YWJhbWExEzARBgNVBAcMCkh1bnRzdmlsbGUxPjA8BgNVBAoMNVNjaWVuY2UgQXBw
bGljYXRpb25zIEludGVybmF0aW9uYWwgQ29ycG9yYXRpb24gKFNBSUMpMSEwHwYD
VQQDDBhTQUlDIElTQSBMYWIgUm9vdCBDQSAtIDGCAhAAMA4GA1UdDwEB/wQEAwID
qDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwCgYIKoZIzj0EAwIDaAAw
ZQIxAIniNQug/cqJHstEz6euZkR+xsYBiYar4e5lQWBAi2Rvi6hl/0FjDnAVtCQ3
D2vZkAIwGNxM6cM0ANRksbLhpHr6JFlIN5DqL4fiQR5eXx9cd0JgbWJHZef2N61Q
gaVAJ46d
-----END CERTIFICATE-----
"""

let doubleCertificate = """
-----BEGIN CERTIFICATE-----
MIIELzCCA7WgAwIBAgICEAAwCgYIKoZIzj0EAwMwgZcxCzAJBgNVBAYTAlVTMRAw
DgYDVQQIDAdBbGFiYW1hMRMwEQYDVQQHDApIdW50c3ZpbGxlMT4wPAYDVQQKDDVT
Y2llbmNlIEFwcGxpY2F0aW9ucyBJbnRlcm5hdGlvbmFsIENvcnBvcmF0aW9uIChT
QUlDKTEhMB8GA1UEAwwYU0FJQyBJU0EgTGFiIFJvb3QgQ0EgLSAxMB4XDTIwMDEw
MTAwMDAwMFoXDTI5MTIyOTAwMDAwMFowgZ8xCzAJBgNVBAYTAlVTMRAwDgYDVQQI
DAdBbGFiYW1hMRMwEQYDVQQHDApIdW50c3ZpbGxlMT4wPAYDVQQKDDVTY2llbmNl
IEFwcGxpY2F0aW9ucyBJbnRlcm5hdGlvbmFsIENvcnBvcmF0aW9uIChTQUlDKTEp
MCcGA1UEAwwgU0FJQyBJU0EgTGFiIEludGVybWVkaWF0ZSBDQSAtIDEwdjAQBgcq
hkjOPQIBBgUrgQQAIgNiAARsZFblGYgTi2uoLVRjAJpIG+0LTgZM4QU4b0Rxdtz5
MfYs0PasP7JudrVPsrhgX6t3kB5XFJmH7YYwM2s6WNsu2NgHf10HOSM12i2Z0UhH
Kg9duDILtdJ2wBG206qg77KjggHIMIIBxDAdBgNVHQ4EFgQUd/wo2kFg7JL8KFj9
yC5qKqVPHQkwgcwGA1UdIwSBxDCBwYAU2Utn6rZ8XNOFdqj1jyycaXoi+nOhgZ2k
gZowgZcxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdBbGFiYW1hMRMwEQYDVQQHDApI
dW50c3ZpbGxlMT4wPAYDVQQKDDVTY2llbmNlIEFwcGxpY2F0aW9ucyBJbnRlcm5h
dGlvbmFsIENvcnBvcmF0aW9uIChTQUlDKTEhMB8GA1UEAwwYU0FJQyBJU0EgTGFi
IFJvb3QgQ0EgLSAxggkA7ozDe3kkk4owEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNV
HQ8BAf8EBAMCAcYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMDAGA1Ud
HwQpMCcwJaAjoCGGH2h0dHA6Ly9jcmwuc2FpYy5jb20vbm90cmVhbC5jcmwwXwYI
KwYBBQUHAQEEUzBRMCwGCCsGAQUFBzAChiBodHRwOi8vb2NzcC5zYWljLmNvbS9u
b3RyZWFsLmNydDAhBggrBgEFBQcwAYYVaHR0cDovL29jc3Auc2FpYy5jb20vMAoG
CCqGSM49BAMDA2gAMGUCMQCIP3pH1fFF08LqYv5UE06LWo4G2jiSZdrnSNfllIS2
J8Bm9BBPfmH+FnzUBWwn7qICMAX3LpID1u3MNR+0m1NOajCt0C7zEUixpaNdFYnR
Wu/1VxyCSP+QTkNSYuHFF6M1Nw==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIC0TCCAligAwIBAgIJAO6Mw3t5JJOKMAoGCCqGSM49BAMDMIGXMQswCQYDVQQG
EwJVUzEQMA4GA1UECAwHQWxhYmFtYTETMBEGA1UEBwwKSHVudHN2aWxsZTE+MDwG
A1UECgw1U2NpZW5jZSBBcHBsaWNhdGlvbnMgSW50ZXJuYXRpb25hbCBDb3Jwb3Jh
dGlvbiAoU0FJQykxITAfBgNVBAMMGFNBSUMgSVNBIExhYiBSb290IENBIC0gMTAe
Fw0yMDAxMDEwMDAwMDJaFw0yOTEyMjkwMDAwMDJaMIGXMQswCQYDVQQGEwJVUzEQ
MA4GA1UECAwHQWxhYmFtYTETMBEGA1UEBwwKSHVudHN2aWxsZTE+MDwGA1UECgw1
U2NpZW5jZSBBcHBsaWNhdGlvbnMgSW50ZXJuYXRpb25hbCBDb3Jwb3JhdGlvbiAo
U0FJQykxITAfBgNVBAMMGFNBSUMgSVNBIExhYiBSb290IENBIC0gMTB2MBAGByqG
SM49AgEGBSuBBAAiA2IABB71zQ0YAGdmyppWdnNEC7oC/UTFs4E5gpLISGP4oqng
ndYEa8hyg91BaKMOEf2DU/FGIMvc+bLt3ccZvSJWP0VTEq+7av5HDw9Lefd5ArBO
H3+6VI6oMoirJU3a28MC2qNuMGwwHQYDVR0OBBYEFNlLZ+q2fFzThXao9Y8snGl6
IvpzMBIGA1UdEwEB/wQIMAYBAf8CAQIwDgYDVR0PAQH/BAQDAgHGMCcGA1UdJQQg
MB4GCCsGAQUFBwMJBggrBgEFBQcDAgYIKwYBBQUHAwEwCgYIKoZIzj0EAwMDZwAw
ZAIwSYpKUIeCQw8uwAnHvVU0iTJFh0m7Pqnjju+iKsH0QfrtNDOUW6UZL9X7JsAm
zWPyAjBDUMPAD+GaUBSV9is4D0NBQGdIDiqcBg98eeiWwaPtlEdsvI3u5CVirt7W
nPa4+pc=
-----END CERTIFICATE-----
"""

final class BIOIteratorTest: XCTestCase {
  func testSingle() {
    let uut = try! BIOIterator(pem: singleCertificate)
    XCTAssertNotNil(uut.next())
    XCTAssertNil(uut.next())
  }

  func testDouble() {
    let uut = try! BIOIterator(pem: doubleCertificate)
    XCTAssertNotNil(uut.next())
    XCTAssertNotNil(uut.next())
    XCTAssertNil(uut.next())
  }

  func testSequence() {
    let col = Array(AnySequence { try! BIOIterator(pem: doubleCertificate) })
    let set = Set(AnySequence { try! BIOIterator(pem: doubleCertificate) })

    XCTAssertEqual(col.count, 2)
    XCTAssertEqual(set.count, 2)
  }
}
